name: Docker Image Build and Push

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag devries/cobol:latest
    - name: Login to docker hub
      env:
        DOCKER_PASSWORD: ${{ secrets.DockerHubPassword }}
      run: echo "$DOCKER_PASSWORD" | docker login --username devries --password-stdin
    - name: Push to docker hub
      run: docker push devries/cobol:latest
      
